version: "3"
services:
  mimic:
    container_name: mimic
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/src
    logging:
      options:
        max-size: "500k"
    ports:
      - "0.0.0.0:3000:3000"
